# Generated by Django 6.0.2 on 2026-05-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('APPLICATION', 'New Application'), ('PAYMENT', 'Payment Received'), ('BATCH', 'Batch Update'), ('TASK', 'New Task'), ('LEAVE', 'Leave Update')], default='INFO', max_length=20),
        ),
    ]
