# Generated by Django 5.2.4 on 2026-05-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='lop_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_days',
            field=models.DecimalField(decimal_places=1, default=30.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_working_days',
            field=models.IntegerField(default=30),
        ),
    ]
