# Generated by Django 5.2.4 on 2026-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeeloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
