# Generated by Django 5.2.4 on 2026-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, help_text='For dropdowns, provide a list of options.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='bank_ifsc_code',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='father_mother_name',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
