# Generated by Django 5.2.4 on 2026-05-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_customfield_remove_employeeprofile_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='permission_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic'), ('ACADEMIC_COORDINATOR', 'Coordinator'), ('TEACHER', 'Teacher'), ('EMPLOYEE', 'General Employee')], default='EMPLOYEE', max_length=30),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('file', 'Image / File')], default='text', max_length=20),
        ),
    ]
