# Generated by Django 5.2.4 on 2026-05-06 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_designation_permission_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General Shift', max_length=50)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='18:00:00')),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('clock_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('clock_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrms.employeeprofile')),
            ],
            options={
                'ordering': ['-date', '-clock_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
