# Generated by Django 5.2.4 on 2026-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_shiftsetting_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftsetting',
            name='allowed_radius_meters',
            field=models.IntegerField(default=200, help_text='Radius in meters from office coordinates'),
        ),
        migrations.AddField(
            model_name='shiftsetting',
            name='office_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='shiftsetting',
            name='office_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
