# Generated by Django 6.0.2 on 2026-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
