# Generated by Django 6.0.2 on 2026-05-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_attendance_clock_in_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hrms.employeeprofile'),
        ),
    ]
