# Generated by Django 6.0.5 on 2026-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_alter_designation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='work_location',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('REMOTE', 'Remote / WFH')], default='OFFICE', max_length=20),
        ),
    ]
