# Generated by Django 5.2.16 on 2026-08-03 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_employeeprofile_work_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FestiveGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Happy Onam! 🌸', max_length=200)),
                ('sub_title', models.CharField(blank=True, help_text='e.g. Wishing you abundance and joy!', max_length=255, null=True)),
                ('message', models.TextField(help_text='Detailed wish or greeting message')),
                ('banner_image', models.ImageField(blank=True, help_text='Upload custom festive banner image', null=True, upload_to='festive_greetings/')),
                ('theme', models.CharField(choices=[('ONAM', 'Onam Festival 🌾🌸'), ('DIWALI', 'Diwali Festival 🪔✨'), ('NEW_YEAR', 'New Year 🎉🥂'), ('CHRISTMAS', 'Christmas 🎄⭐'), ('EID', 'Eid Mubarak 🌙✨'), ('BIRTHDAY', 'Birthday Wish 🎂🎈'), ('HOLI', 'Holi Colors 🎨✨'), ('COMPANY_MILESTONE', 'Company Milestone 🏆🚀'), ('CUSTOM', 'Custom Festival / Announcement 🌟')], default='ONAM', max_length=30)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users & Students'), ('EMPLOYEES', 'All Staff & Employees'), ('SALES', 'Sales Team'), ('MENTORS', 'Mentors & Academic Staff'), ('STUDENTS', 'Students Only')], default='ALL', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_greetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
