# Generated by Django 5.2.16 on 2026-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_companypostcomment_festivegreetingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='permission_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic'), ('ACADEMIC_COORDINATOR', 'Coordinator'), ('TEACHER', 'Teacher'), ('EMPLOYEE', 'General Employee'), ('MARKETER', 'Digital Marketer')], default='EMPLOYEE', max_length=30),
        ),
    ]
