# Generated by Django 6.0.2 on 2026-10-03 04:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_alter_designation_permission_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/', validators=[core.validators.validate_profile_photo_file]),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employee_docs/', validators=[core.validators.validate_employee_document_file]),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[core.validators.validate_profile_photo_file]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/', validators=[core.validators.validate_receipt_file]),
        ),
        migrations.AlterField(
            model_name='festivegreeting',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Upload custom festive banner image', null=True, upload_to='festive_greetings/', validators=[core.validators.validate_profile_photo_file]),
        ),
    ]
