# Generated by Django 6.0.2 on 2026-05-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_webhookendpoint_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinteraction',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/%Y/%m/'),
        ),
    ]
