# Generated by Django 6.0.2 on 2026-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinteraction',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='call_duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='call_status',
            field=models.CharField(blank=True, choices=[('CONNECTED', 'Connected'), ('MISSED', 'Missed/Unanswered')], max_length=20, null=True),
        ),
    ]
