# Generated by Django 5.2.16 on 2026-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_leadinteraction_call_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='section',
            field=models.CharField(choices=[('CAREER_ACADEMY', 'Career Academy'), ('REGULAR', 'Regular'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
    ]
