# Generated by Django 5.2.16 on 2026-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_campaign_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='meta_access_token',
            field=models.TextField(blank=True, help_text='Meta Page Access Token for Conversions API - keep this secret!', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_ad_id',
            field=models.CharField(blank=True, help_text='Facebook Ad ID (optional, for more precise matching)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_auto_import',
            field=models.BooleanField(default=False, help_text='If enabled, leads from this Meta form auto-import into CRM'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_form_id',
            field=models.CharField(blank=True, help_text='Facebook Lead Ad Form ID for auto-matching incoming leads', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID that this campaign belongs to', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_pixel_id',
            field=models.CharField(blank=True, help_text='Facebook Pixel ID for Conversions API', max_length=100, null=True),
        ),
    ]
