# Generated by Django 5.2.16 on 2026-08-06 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_campaign_meta_access_token_campaign_meta_ad_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_assign_to',
            field=models.ManyToManyField(blank=True, help_text='Sales representatives to auto-assign incoming leads to (Round-Robin)', related_name='assigned_meta_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
