# Generated by Django 5.2.16 on 2026-08-08 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_campaign_auto_assign_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='secret_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret token for Campaign-linked webhooks', null=True),
        ),
    ]
