# Generated by Django 5.2.16 on 2026-08-08 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_campaign_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='secret_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret token for Campaign-linked webhooks', null=True, unique=True),
        ),
    ]
