# Generated by Django 5.2.16 on 2026-08-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_campaign_secret_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_last_synced_row',
            field=models.IntegerField(default=0, help_text='The last row index imported from this sheet'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_sheet_name',
            field=models.CharField(blank=True, help_text='Sheet Tab name (e.g., Sheet1)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_spreadsheet_id',
            field=models.CharField(blank=True, help_text='Google Sheets Spreadsheet ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
