# Generated by Django 5.2.16 on 2026-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_campaign_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='google_auto_sync',
            field=models.BooleanField(default=False, help_text='Automatically sync leads from this sheet in the background'),
        ),
    ]
