# Generated by Django 6.0.2 on 2026-09-15 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_student_email'),
        ('crm', '0013_campaign_google_auto_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinteraction',
            name='caller_number',
            field=models.CharField(blank=True, db_index=True, help_text='Caller phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, help_text='Customer / Lead phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='is_matched',
            field=models.BooleanField(default=False, help_text='Whether this call is linked to an existing CRM Student/Lead'),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='mobile_call_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique client-generated mobile call ID for deduplication', max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='provider_call_id',
            field=models.CharField(blank=True, db_index=True, help_text='Provider call ID', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='provider_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Provider event ID', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='receiver_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receiver / Destination phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='recording_url',
            field=models.CharField(blank=True, help_text='Remote/telephony audio recording URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinteraction',
            name='telephony_provider',
            field=models.CharField(blank=True, default='MOBILE_APP', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='call_direction',
            field=models.CharField(blank=True, choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], default='OUTGOING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='call_status',
            field=models.CharField(blank=True, choices=[('CONNECTED', 'Connected'), ('MISSED', 'Missed'), ('REJECTED', 'Rejected'), ('UNANSWERED', 'Unanswered'), ('BUSY', 'Busy'), ('FAILED', 'Failed')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leadinteraction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to='core.student'),
        ),
    ]
