# Generated by Django 6.0.2 on 2026-09-16 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_leadinteraction_caller_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_assigned_bde',
            field=models.ForeignKey(blank=True, help_text='The last sales representative assigned a lead for this campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_assigned_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
