# Generated by Django 6.0.2 on 2026-09-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_campaign_last_assigned_bde'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinteraction',
            name='audio_file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of audio content to prevent duplicate cross-call attachment', max_length=64, null=True),
        ),
    ]
