# Generated by Django 6.0.2 on 2026-10-03 04:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_leadinteraction_audio_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinteraction',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/%Y/%m/', validators=[core.validators.validate_audio_recording_file]),
        ),
    ]
