# Generated by Django 6.0.2 on 2026-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales Module'), ('MENTOR', 'Mentor Module'), ('STUDENT', 'Student Portal'), ('ACADEMIC', 'Academic Module'), ('ADMIN', 'Admin Module'), ('ANALYTICS', 'Analytics & Reports'), ('TEACHER', 'Teacher Module')], max_length=20),
        ),
    ]
