# Generated by Django 5.2.4 on 2026-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_lms_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales & Leads'), ('MENTOR', 'Mentor Module'), ('STUDENT', 'Student Portal'), ('ACADEMIC_HIERARCHY', 'Academic Hierarchy'), ('COORDINATOR', 'Coordinator Module'), ('TEACHER', 'Teacher Module'), ('COURSES', 'Courses & Batches'), ('ANALYTICS', 'Analytics & Reports'), ('WORKFORCE', 'HRMS: Workforce Hub'), ('ATTENDANCE', 'HRMS: Attendance'), ('PAYROLL', 'HRMS: Payroll'), ('STAFF_DIRECTORY', 'Staff Directory'), ('ADMIN', 'Administrator Portal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('EMPLOYEE', 'General Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('EMPLOYEE', 'General Employee')], default='STUDENT', max_length=20),
        ),
    ]
