# Generated by Django 5.2.4 on 2026-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_batch_id_alter_course_id_alter_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
