# Generated by Django 5.2.4 on 2026-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_require_payment_program_registration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
