# Generated by Django 6.0.2 on 2026-10-03 04:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[core.validators.validate_receipt_file]),
        ),
    ]
