# Generated by Django 6.0.2 on 2026-06-27 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_alter_attendance_date'),
        ('leaves', '0002_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_leaves', to='hrms.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Manager'), ('PENDING_HR', 'Pending HR'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_MANAGER', max_length=20),
        ),
    ]
