# Generated by Django 5.2.4 on 2026-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0005_dynamicfield_field_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('file', 'File Upload'), ('payment', 'Payment Section')], max_length=20),
        ),
    ]
