# Generated by Django 6.0.2 on 2026-06-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslip_loan_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='provident_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
