# Generated by Django 6.0.2 on 2026-06-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_attendance_is_face_verified_and_more'),
        ('payroll', '0005_payslip_professional_tax_payslip_provident_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='tds_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='tax_regime',
            field=models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime')], default='NEW', max_length=5),
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=9)),
                ('regime', models.CharField(choices=[('OLD', 'Old Regime'), ('NEW', 'New Regime')], default='NEW', max_length=5)),
                ('sec_80c', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 80C')),
                ('sec_80d', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 80D')),
                ('sec_24b', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 24(b) Home Loan Interest')),
                ('sec_80ccd_1b', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 80CCD(1B) NPS')),
                ('sec_80e', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 80E Education Loan')),
                ('sec_80g', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 80G Donations')),
                ('sec_80tta', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Section 80TTA Savings Interest')),
                ('annual_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('landlord_pan', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='tax_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declarations', to='hrms.employeeprofile')),
            ],
            options={
                'unique_together': {('employee', 'financial_year')},
            },
        ),
    ]
