# Generated by Django 6.0.2 on 2026-10-03 04:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payslip_tds_deduction_salarystructure_tax_regime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdeclaration',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='tax_proofs/', validators=[core.validators.validate_tax_proof_file]),
        ),
    ]
