# Generated by Django 5.2.4 on 2026-02-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('STUDENT', 'Student')], max_length=20)),
                ('module', models.CharField(choices=[('SALES', 'Sales Module'), ('MENTOR', 'Mentor Module'), ('STUDENT', 'Student Portal'), ('ACADEMIC', 'Academic Module'), ('ADMIN', 'Admin Module')], max_length=20)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
