# Generated by Django 5.2.4 on 2026-03-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rolepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales Module'), ('MENTOR', 'Mentor Module'), ('STUDENT', 'Student Portal'), ('ACADEMIC', 'Academic Module'), ('ADMIN', 'Admin Module'), ('ANALYTICS', 'Analytics & Reports')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
