# Generated by Django 5.2.4 on 2026-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_rolepermission_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
