# Generated by Django 5.2.4 on 2026-04-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lms_teacher_id',
            field=models.CharField(blank=True, help_text='Wise LMS Teacher ID', max_length=100, null=True),
        ),
    ]
