# Generated by Django 5.2.16 on 2026-08-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_sales_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('EMPLOYEE', 'General Employee'), ('MARKETER', 'Digital Marketer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SALES', 'Sales User'), ('MENTOR', 'Mentor'), ('ACADEMIC', 'Academic User'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('EMPLOYEE', 'General Employee'), ('MARKETER', 'Digital Marketer')], default='STUDENT', max_length=20),
        ),
    ]
