# Generated by Django 5.2.16 on 2026-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_rolepermission_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('SALES', 'Sales & Leads'), ('CRM_DASHBOARD', 'CRM Dashboard'), ('CRM_CAMPAIGNS', 'CRM Campaigns'), ('CRM_PIPELINE', 'CRM Pipeline'), ('CRM_LEADS_TABLE', 'CRM Leads Table'), ('CRM_TASKS', 'CRM Tasks'), ('CRM_REPORTS', 'CRM Team Reports'), ('CRM_CALL_ANALYTICS', 'CRM Call Analytics'), ('MENTOR', 'Mentor Module'), ('STUDENT', 'Student Portal'), ('ACADEMIC_HIERARCHY', 'Academic Hierarchy'), ('COORDINATOR', 'Coordinator Module'), ('TEACHER', 'Teacher Module'), ('COURSES', 'Courses & Batches'), ('ANALYTICS', 'Analytics & Reports'), ('WORKFORCE', 'HRMS: Workforce Hub'), ('ATTENDANCE', 'HRMS: Attendance'), ('PAYROLL', 'HRMS: Payroll'), ('STAFF_DIRECTORY', 'Staff Directory'), ('ADMIN', 'Administrator Portal')], max_length=20),
        ),
    ]
