# Generated by Django 5.2.4 on 2026-02-17 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_corr_address_alter_student_corr_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='sub_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subprogram'),
        ),
    ]
