# Generated by Django 5.2.4 on 2026-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_batch_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='require_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='program',
            name='require_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='require_payment',
            field=models.BooleanField(default=False),
        ),
    ]
