# Generated by Django 5.2.4 on 2026-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_student_first_name_alter_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuspart',
            name='module',
            field=models.CharField(blank=True, help_text='e.g., Module A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syllabuspart',
            name='semester',
            field=models.CharField(blank=True, help_text='e.g., Semester 1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='syllabuspart',
            name='subject',
            field=models.CharField(blank=True, help_text='e.g., Theory', max_length=100, null=True),
        ),
    ]
