# Generated by Django 5.2.4 on 2026-03-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_syllabuspart_module_syllabuspart_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='batch_resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.batch')),
            ],
        ),
    ]
