# Generated by Django 5.2.4 on 2026-03-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_exam_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('UNIT', 'Unit Test'), ('PERIODIC', 'Periodic Assessment'), ('MIDTERM', 'Midterm Examination'), ('FINAL', 'Final Examination'), ('ASSIGNMENT', 'Assignment/Project'), ('VIVA', 'Viva Voce')], default='UNIT', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
