# Generated by Django 5.2.4 on 2026-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_question_questionoption_studentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='lms_batch_id',
            field=models.CharField(blank=True, help_text='Wise LMS Class ID', max_length=100, null=True),
        ),
    ]
