# Generated by Django 6.0.2 on 2026-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_classsession_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lms_course_names',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
