# Generated by Django 6.0.2 on 2026-05-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_student_lms_course_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lead_status',
            field=models.CharField(choices=[('NEW', 'New Lead'), ('FOLLOW_UP', 'Follow-up'), ('PAYMENT_PENDING', 'Payment Pending'), ('ENROLLED', 'Enrolled'), ('DROPPED', 'Dropped')], default='NEW', max_length=20),
        ),
    ]
