# Generated by Django 6.0.2 on 2026-05-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_student_assigned_to'),
        ('crm', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.campaign'),
        ),
    ]
