# Generated by Django 6.0.2 on 2026-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_student_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lead_status',
            field=models.CharField(default='NEW', max_length=50),
        ),
    ]
