# Generated by Django 6.0.2 on 2026-06-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_student_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_BREAK', 'On Break')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentBreakHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start_date', models.DateField(auto_now_add=True)),
                ('rejoin_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active_break', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_history', to='core.student')),
            ],
        ),
    ]
