# Generated by Django 6.0.2 on 2026-06-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_batchassignmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_BREAK', 'On Break'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20),
        ),
    ]
