# Generated by Django 6.0.2 on 2026-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_student_academic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discontinued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
