# Generated by Django 6.0.2 on 2026-06-14 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_student_discontinued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbreakhistory',
            name='break_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
