# Generated by Django 5.2.16 on 2026-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sales_section',
            field=models.CharField(choices=[('CAREER_ACADEMY', 'Career Academy'), ('REGULAR', 'Regular'), ('BOTH', 'Both')], default='BOTH', max_length=20),
        ),
    ]
