# Generated by Django 5.2.16 on 2026-07-28 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_studentteacherhandover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FEE_UPDATE', 'Fee Structure Updated'), ('PAYMENT_ADD', 'Payment Recorded'), ('PAYMENT_EDIT', 'Payment Edited'), ('PAYMENT_DELETE', 'Payment Deleted')], max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Which field was changed', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_edits_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_edit_logs', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
