# Generated by Django 5.2.16 on 2026-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_fee_edit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lead_quality',
            field=models.CharField(choices=[('UNKNOWN', 'Not Reviewed'), ('QUALITY', 'Quality Lead'), ('FAKE', 'Fake / Junk Lead')], default='UNKNOWN', help_text='Sales rep feedback sent back to Meta for ad optimization', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='meta_lead_id',
            field=models.CharField(blank=True, help_text='Facebook Lead Ad lead_id for Conversions API feedback', max_length=200, null=True, unique=True),
        ),
    ]
