# Generated by Django 5.2.16 on 2026-08-22 11:25

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_student_lead_quality_student_meta_lead_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=core.models.NormalizedMobileField(blank=True, max_length=15, null=True),
        ),
    ]
