# Generated by Django 5.2.16 on 2026-08-22 11:34

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=core.models.NormalizedEmailField(blank=True, max_length=254, null=True),
        ),
    ]
