# Generated by Django 6.0.2 on 2026-10-03 04:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchresource',
            name='file',
            field=models.FileField(upload_to='batch_resources/', validators=[core.validators.validate_batch_resource_file]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='student_docs/', validators=[core.validators.validate_student_document_file]),
        ),
    ]
