# Generated by Django 6.0.2 on 2026-02-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown'), ('file', 'File Upload')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text='Dropdown options as list of strings', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conditional_rule', models.JSONField(blank=True, help_text='Rules for visibility', null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='core.program')),
                ('sub_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='core.subprogram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentDynamicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_builder.dynamicfield')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_values', to='core.student')),
            ],
        ),
    ]
