# Generated by Django 5.2.4 on 2026-02-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_batch_id_alter_course_id_alter_document_id_and_more'),
        ('forms_builder', '0002_alter_dynamicfield_id_alter_studentdynamicvalue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='core.course'),
        ),
    ]
