# Generated by Django 5.2.4 on 2026-03-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0003_dynamicfield_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentdynamicvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
