# Generated by Django 5.2.4 on 2026-03-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0004_alter_dynamicfield_id_alter_studentdynamicvalue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='field_group',
            field=models.CharField(choices=[('INITIAL', 'Initial Application (Sales)'), ('ACADEMIC', 'Academic/Post-Admission')], default='INITIAL', max_length=20),
        ),
    ]
