# Generated by Django 5.2.4 on 2026-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0006_alter_dynamicfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='validation_rules',
            field=models.JSONField(blank=True, help_text="Validation rules (JSON) e.g. {'pattern': '^[0-9]{10}$', 'message': 'Invalid phone'}", null=True),
        ),
    ]
